In [131]:
import numpy as np
import math

In [132]:
A = np.array([[1, 1, -2, 2],
             [1, -1, -1, 2],
             [-2, -1, 1, 2],
             [2, 2, 2, 1]])



In [133]:
c= A[1:, 0, np.newaxis]
for i in c:
    print(i)

[1]
[-2]
[2]


In [134]:
def gen_U(a):
  

    norm2 = 0
    t = a.shape[0]
    
    l = [[0] for i in range(t)]
    l[0] = [1]
    for i in a:
        norm2 += i**2
        
    norm2 = math.sqrt(norm2)    
        
    if a[0] <0:
           u=   a - norm2 * 1
    elif a[0] >= 0:
        u = a+ norm2 * np.array(l)
        
    i = np.identity(t) 
    h = i -  (2*(u@ u.T)/ (u.T @ u))
    return h
    

In [135]:
p = gen_U(c)


In [136]:
def genvec_house(a):


    u = a/ (a[0] +np.copysign(np.linalg.norm(a), a[0]))

    u[0] = 1
    tau = 2*(u@ u.T)/ (u.T @ u)
    
    return u,tau

In [133]:
l = [[0] for i in range(3)]

In [137]:
l[0] = [1]

In [152]:
l

[[1], [0], [0]]

In [153]:
np.array(l)

array([[1],
       [0],
       [0]])

In [123]:
A = np.array([[1, 1, -2, 2],
             [1, -1, -1, 2],
             [-2, -1, 1, 2],
             [2, 2, 2, 1]  ])



In [124]:
c= np.array([[0,0,0,0]])
c2 = np.array([1,0,0,0,0
              ])
c

array([[0, 0, 0, 0]])

In [125]:
f = np.append(c, A, axis= 0 )
np.insert(f,0,c2, axis =1)



array([[ 1,  0,  0,  0,  0],
       [ 0,  1,  1, -2,  2],
       [ 0,  1, -1, -1,  2],
       [ 0, -2, -1,  1,  2],
       [ 0,  2,  2,  2,  1]])

In [116]:
A

array([[ 1,  1, -2,  2],
       [ 1, -1, -1,  2],
       [-2, -1,  1,  2],
       [ 2,  2,  2,  1]])

In [128]:
def gen_H(a):
    n = a.shape[0]
    c = np.array([[0 for i in range(n)]])
    c2 = np.array([ 0 for i in range(n+1)])
    
    f = np.append(c , a, axis =0)
    H = np.insert(f, 0 , c2, axis = 1)
    H[0,0] =1 
    return H

In [140]:
H= gen_H(p)

In [100]:
def houseHolder2(m):    
    l = len(m)
    for i in range(0, l - 1):
        I = np.eye(l - i)
        ai = m[:, i] 
        abs = np.linalg.norm(ai[i:l]) 
        sign = np.sign(m[i, i])
        vi = np.array([ai[i:l]]).T + sign * abs * np.array([I[:, 0]]).T
        Qi = I - 2 * (vi @ vi.T) / (vi.T @ vi)
        J = np.eye(l)
        J[i:l, i:l] = Qi
        m = J@m
    return m  

In [142]:
H @ A @ H.T

array([[ 1.00000000e+00, -3.00000000e+00, -2.22044605e-16,
         2.22044605e-16],
       [-3.00000000e+00,  3.33333333e-01, -1.33333333e+00,
         1.00000000e+00],
       [-2.22044605e-16, -1.33333333e+00,  1.00000000e+00,
         2.66666667e+00],
       [ 2.22044605e-16,  1.00000000e+00,  2.66666667e+00,
        -3.33333333e-01]])

In [172]:
houseHolder2(A)

array([[-3.16227766e+00, -1.89736660e+00,  3.16227766e-01,
        -6.32455532e-01],
       [-1.25737386e-16,  1.84390889e+00,  1.41004798e+00,
        -6.50791373e-01],
       [ 4.99847827e-17, -7.60989311e-17,  2.81278593e+00,
        -3.13693598e-01],
       [-7.96463094e-17, -3.67449905e-17, -3.85272685e-16,
         3.47535134e+00]])

In [173]:
from numpy import dot,diagonal,outer,identity
from math import sqrt

def householder(a): 
    n = len(a)
    for k in range(n-2):
        u = a[k+1:n,k]
        uMag = sqrt(dot(u,u))
        if u[0] < 0.0: uMag = -uMag
        u[0] = u[0] + uMag
        h = dot(u,u)/2.0
        v = dot(a[k+1:n,k+1:n],u)/h
        g = dot(u,v)/(2.0*h)
        v = v - g*u
        a[k+1:n,k+1:n] = a[k+1:n,k+1:n] - outer(v,u) \
                         - outer(u,v)
        a[k,k+1] = -uMag
    return diagonal(a),diagonal(a,1)

def computeP(a): 
    n = len(a)
    p = identity(n)*1.0
    for k in range(n-2):
        u = a[k+1:n,k]
        h = dot(u,u)/2.0
        v = dot(p[1:n,k+1:n],u)/h           
        p[1:n,k+1:n] = p[1:n,k+1:n] - outer(v,u)
    return p
      

In [174]:
A

array([[ 1,  1, -2,  2],
       [ 1, -1, -1,  2],
       [-2, -1,  1,  2],
       [ 2,  2,  2,  1]])

In [181]:
householder(A)

(array([ 1,  2, -1,  0]), array([-4, -2,  0]))

In [178]:
 p  = computeP(A)

In [180]:
p @ A @ p.T

array([[ 1.00000000e+00,  1.00000000e+00,  1.11022302e-16,
         4.00000000e+00],
       [-1.33333333e+00, -1.33333333e+00,  1.00000000e+00,
        -3.33333333e-01],
       [ 4.66666667e+00, -1.33333333e+00,  2.00000000e+00,
         6.66666667e-01],
       [-6.66666667e-01,  1.33333333e+00,  2.00000000e+00,
         3.33333333e-01]])