In [13]:
import numpy as np


import transforms.genh as gh
import transforms.genHbyh as Hbyh

In [14]:

A = np.array([[i*j+ i*i + j*j for i in range(1,11)] 
for j in range(1,11)])
A

array([[  3,   7,  13,  21,  31,  43,  57,  73,  91, 111],
       [  7,  12,  19,  28,  39,  52,  67,  84, 103, 124],
       [ 13,  19,  27,  37,  49,  63,  79,  97, 117, 139],
       [ 21,  28,  37,  48,  61,  76,  93, 112, 133, 156],
       [ 31,  39,  49,  61,  75,  91, 109, 129, 151, 175],
       [ 43,  52,  63,  76,  91, 108, 127, 148, 171, 196],
       [ 57,  67,  79,  93, 109, 127, 147, 169, 193, 219],
       [ 73,  84,  97, 112, 129, 148, 169, 192, 217, 244],
       [ 91, 103, 117, 133, 151, 171, 193, 217, 243, 271],
       [111, 124, 139, 156, 175, 196, 219, 244, 271, 300]])

In [15]:


c= A[1:, 0, np.newaxis]
c

array([[  7],
       [ 13],
       [ 21],
       [ 31],
       [ 43],
       [ 57],
       [ 73],
       [ 91],
       [111]])

In [16]:

def genTriplematrix(A):

    p = np.identity(10)
    # print(p)
    for i in range(1,6):
        c= A[i:, i-1, np.newaxis]
        # print(c)
        h = gh.genUh(c)
        # print(h)
        H= Hbyh.gen_H(h)
        # print(H)
        p =H @ p
        
        
        
        
        
        A = H @ A @ H.T
 
    return  A ,p
      

        

In [17]:
A , p = genTriplematrix(A)


In [18]:
A

array([[ 3.00000000e+00, -1.80690343e+02, -3.55837461e-15,
         1.38170752e-14,  4.00196844e-15, -8.34770426e-15,
         2.37115608e-17, -2.47172849e-16,  7.02564786e-16,
         2.89550648e-15],
       [-1.80690343e+02,  1.15406303e+03,  3.31384740e+02,
        -3.22484650e-14,  5.00382622e-14, -4.88879710e-15,
         3.95055440e-14, -4.35569807e-14,  1.52125456e-14,
         1.42618944e-14],
       [-3.55837461e-15,  3.31384740e+02, -3.41696413e+00,
         3.26438668e+00,  5.79055032e-16,  2.36474274e-15,
        -8.79397650e-15,  1.51738019e-15,  1.20213923e-15,
         8.00505055e-15],
       [ 1.38170752e-14,  1.12493121e-14,  3.26438668e+00,
         1.35393004e+00,  2.82378252e-15, -1.76762732e-15,
        -7.66289444e-15,  9.17041739e-16, -1.79780502e-14,
         5.02061283e-15],
       [ 4.00196844e-15, -1.12437734e-14,  9.58326051e-17,
         1.06293911e-14, -6.42589853e-15,  4.39713204e-16,
        -9.13089998e-15, -7.89894818e-15,  1.42863069e-14,
        -1.

In [19]:
p

array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        , -0.03874031, -0.07194629, -0.11622093, -0.17156423,
        -0.23797619, -0.31545681, -0.4040061 , -0.50362404, -0.61431064],
       [ 0.        , -0.4905566 , -0.47005862, -0.42594387, -0.35821233,
        -0.26686402, -0.15189892, -0.01331705,  0.14888161,  0.33469704],
       [ 0.        ,  0.64688444,  0.22947005, -0.07700857, -0.27255141,
        -0.35715849, -0.33082979, -0.19356532,  0.05463493,  0.41377094],
       [ 0.        ,  0.36907508, -0.34397229, -0.10118708, -0.48683736,
         0.24689366,  0.62018139, -0.06641073, -0.21878278, -0.01895991],
       [ 0.        , -0.36937309,  0.44430886,  0.50222703, -0.59073631,
        -0.18605653,  0.170258  , -0.00851659,  0.03562741,  0.00226122],
       [ 0.        , -0.10085204,  0.3807606 , -0.44616206,  0.27792927,
        -0.46065088,  0.56438921, -0.18823962

In [20]:
p @ A @ p.T

array([[   3.        ,    7.        ,   88.63883937, -116.88577085,
         -66.68830317,   66.74215091,   18.22298885,  -10.19764014,
          -3.57164611,   41.59570165],
       [   7.        ,    3.63450895,   39.89240716,  -47.29072409,
         -20.7988181 ,   19.36043697,    2.14942955,   -7.49265356,
          -4.68707572,   11.68052914],
       [  88.63883937,   39.89240716,  431.3464688 , -504.07938382,
        -210.38001565,  193.45912844,   11.93191866,  -87.21252381,
         -57.02631388,  114.33259053],
       [-116.88577085,  -47.29072409, -504.07938382,  581.02324714,
         230.15124506, -208.73277095,   -2.01891638,  108.33775422,
          73.24616529, -120.81786238],
       [ -66.68830317,  -20.7988181 , -210.38001565,  230.15124506,
          72.89950065,  -61.14118107,   15.99243729,   53.99700449,
          39.67755114,  -31.92934148],
       [  66.74215091,   19.36043697,  193.45912844, -208.73277095,
         -61.14118107,   49.80921403,  -19.36914739,  -52