In [5]:
import numpy as np 
import scipy.linalg as lg 

## LU Decoposition

In [6]:
A = np.array([[95, 54, 26, 6, 10],[70, 40, 20, 5, 8],
             [46, 26, 14, 4, 6],[25, 14, 8, 3, 4],
             [9, 5, 3, 2, 2]])

In [7]:
A

array([[95, 54, 26,  6, 10],
       [70, 40, 20,  5,  8],
       [46, 26, 14,  4,  6],
       [25, 14,  8,  3,  4],
       [ 9,  5,  3,  2,  2]])

In [8]:
A, L, U = lg.lu(A)

In [9]:
A


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.]])

In [10]:
L

array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.73684211,  1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.48421053, -0.7       ,  1.        ,  0.        ,  0.        ],
       [ 0.09473684, -0.55      ,  0.5       ,  1.        ,  0.        ],
       [ 0.26315789, -1.        ,  1.        ,  0.5       ,  1.        ]])

In [11]:
U

array([[95.        , 54.        , 26.        ,  6.        , 10.        ],
       [ 0.        ,  0.21052632,  0.84210526,  0.57894737,  0.63157895],
       [ 0.        ,  0.        ,  2.        ,  1.5       ,  1.6       ],
       [ 0.        ,  0.        ,  0.        ,  1.        ,  0.6       ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.1       ]])

In [27]:
A = np.array([[95, 54, 26, 6, 10],[70, 40, 20, 5, 8],
             [46, 26, 14, 4, 6],[25, 14, 8, 3, 4],
             [9, 5, 3, 2, 2]])

In [44]:


def luDecomposition(mat, n):
 
    lower = [[0 for x in range(n)]
             for y in range(n)]
    upper = [[0 for x in range(n)]
             for y in range(n)]
 
    # Decomposing matrix into Upper
    # and Lower triangular matrix
    for i in range(n):
 
        # Upper Triangular
        for k in range(i, n):
 
            # Summation of L(i, j) * U(j, k)
            sum = 0
            for j in range(i):
                sum += (lower[i][j] * upper[j][k])
 
            # Evaluating U(i, k)
            upper[i][k] = mat[i][k] - sum
 
        # Lower Triangular
        for k in range(i, n):
            if (i == k):
                lower[i][i] = 1  # Diagonal as 1
            else:
 
                # Summation of L(k, j) * U(j, i)
                sum = 0
                for j in range(i):
                    sum += (lower[k][j] * upper[j][i])
 
                # Evaluating L(k, i)
                lower[k][i] = int((mat[k][i] - sum) /
                                  upper[i][i])




    return lower," fdfd " ,upper

In [45]:
luDecomposition(A,5)

([[1, 0, 0, 0, 0],
  [0, 1, 0, 0, 0],
  [0, 0, 1, 0, 0],
  [0, 0, 0, 1, 0],
  [0, 0, 0, 0, 1]],
 ' fdfd ',
 [[95, 54, 26, 6, 10],
  [0, 40, 20, 5, 8],
  [0, 0, 14, 4, 6],
  [0, 0, 0, 3, 4],
  [0, 0, 0, 0, 2]])

In [39]:
upper

NameError: name 'upper' is not defined