In [2]:
import numpy as np 
import scipy.linalg as lg 

# Q1

## LU Decoposition

  \begin{bmatrix}a_{11}&a_{12}&a_{13}\\a_{21}&a_{22}&a_{23}\\a_{31}&a_{32}&a_{33}\end{bmatrix} 
 
\begin{bmatrix}\ell _{11}&0&0\\\ell _{21}&\ell _{22}&0\\\ell _{31}&\ell _{32}&\ell _{33}\end{bmatrix}

\begin{bmatrix}u_{11}&u_{12}&u_{13}\\0&u_{22}&u_{23}\\0&0&u_{33}\end{bmatrix}

In [3]:
A = np.array([[95, 54, 26, 6, 10],[70, 40, 20, 5, 8],
             [46, 26, 14, 4, 6],[25, 14, 8, 3, 4],
             [9, 5, 3, 2, 2]])

In [4]:
A

array([[95, 54, 26,  6, 10],
       [70, 40, 20,  5,  8],
       [46, 26, 14,  4,  6],
       [25, 14,  8,  3,  4],
       [ 9,  5,  3,  2,  2]])

In [5]:
A, L, U = lg.lu(A)

In [6]:
L

array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.73684211,  1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.48421053, -0.7       ,  1.        ,  0.        ,  0.        ],
       [ 0.09473684, -0.55      ,  0.5       ,  1.        ,  0.        ],
       [ 0.26315789, -1.        ,  1.        ,  0.5       ,  1.        ]])

In [7]:
U

array([[95.        , 54.        , 26.        ,  6.        , 10.        ],
       [ 0.        ,  0.21052632,  0.84210526,  0.57894737,  0.63157895],
       [ 0.        ,  0.        ,  2.        ,  1.5       ,  1.6       ],
       [ 0.        ,  0.        ,  0.        ,  1.        ,  0.6       ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.1       ]])

In [8]:
A = np.array([[95, 54, 26, 6, 10],[70, 40, 20, 5, 8],
             [46, 26, 14, 4, 6],[25, 14, 8, 3, 4],
             [9, 5, 3, 2, 2]])

In [9]:
n = A.shape[0]
u = np.zeros((n,n), dtype=np.double)
l = np.eye(n, dtype=np.double)

def firstQ1(A):
    
    n = A.shape[0]
    for k in range(n):
        
        u[k, k:] = A[k, k:] - l[k,:k] @ u[:k,k:]
        
        l[(k+1):,k] = (A[(k+1):,k] - l[(k+1):,:] @ u[:,k]) / u[k, k]
        
        
        
    return l,u


In [10]:
firstQ1(A)

(array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.73684211,  1.        ,  0.        ,  0.        ,  0.        ],
        [ 0.48421053, -0.7       ,  1.        ,  0.        ,  0.        ],
        [ 0.26315789, -1.        ,  1.        ,  1.        ,  0.        ],
        [ 0.09473684, -0.55      ,  0.5       ,  2.        ,  1.        ]]),
 array([[95.        , 54.        , 26.        ,  6.        , 10.        ],
        [ 0.        ,  0.21052632,  0.84210526,  0.57894737,  0.63157895],
        [ 0.        ,  0.        ,  2.        ,  1.5       ,  1.6       ],
        [ 0.        ,  0.        ,  0.        ,  0.5       ,  0.4       ],
        [ 0.        ,  0.        ,  0.        ,  0.        , -0.2       ]]))

In [11]:
l

array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.73684211,  1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.48421053, -0.7       ,  1.        ,  0.        ,  0.        ],
       [ 0.26315789, -1.        ,  1.        ,  1.        ,  0.        ],
       [ 0.09473684, -0.55      ,  0.5       ,  2.        ,  1.        ]])

In [12]:
u

array([[95.        , 54.        , 26.        ,  6.        , 10.        ],
       [ 0.        ,  0.21052632,  0.84210526,  0.57894737,  0.63157895],
       [ 0.        ,  0.        ,  2.        ,  1.5       ,  1.6       ],
       [ 0.        ,  0.        ,  0.        ,  0.5       ,  0.4       ],
       [ 0.        ,  0.        ,  0.        ,  0.        , -0.2       ]])

In [13]:
l @ u

array([[95., 54., 26.,  6., 10.],
       [70., 40., 20.,  5.,  8.],
       [46., 26., 14.,  4.,  6.],
       [25., 14.,  8.,  3.,  4.],
       [ 9.,  5.,  3.,  2.,  2.]])

### QR Decompostion


In [14]:
A = np.array([[95, 54, 26, 6, 10],[70, 40, 20, 5, 8],
             [46, 26, 14, 4, 6],[25, 14, 8, 3, 4],
             [9, 5, 3, 2, 2]])

In [15]:
Q1 , R1 = lg.qr(A)

In [16]:
Q1

array([[-7.34099782e-01,  2.66652690e-02,  6.78517850e-01,
        -7.67290867e-16,  2.74528934e-16],
       [-5.40915629e-01, -5.79162849e-01, -5.62464955e-01,
        -1.84448932e-01, -1.46943672e-01],
       [-3.55458842e-01,  4.32079264e-01, -4.01557259e-01,
         4.71237270e-01,  5.51038769e-01],
       [-1.93184153e-01,  6.05828118e-01, -2.32817772e-01,
        -4.04597656e-02, -7.34718358e-01],
       [-6.95462951e-02,  3.31872202e-01, -8.82856385e-02,
        -8.61555009e-01,  3.67359179e-01]])

In [17]:
R1

array([[-1.29410201e+02, -7.35722529e+01, -3.66354428e+01,
        -9.24965725e+00, -1.47129051e+01],
       [ 0.00000000e+00, -3.51573929e-01,  1.00139125e+00,
         1.47372318e+00,  1.31288235e+00],
       [ 0.00000000e+00,  0.00000000e+00, -1.35703570e+00,
        -1.22247130e+00, -1.23172705e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -8.81784892e-01, -5.33116912e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00, -7.34718358e-02]])

In [18]:
Q1 @ R1

array([[95., 54., 26.,  6., 10.],
       [70., 40., 20.,  5.,  8.],
       [46., 26., 14.,  4.,  6.],
       [25., 14.,  8.,  3.,  4.],
       [ 9.,  5.,  3.,  2.,  2.]])

In [19]:
A = np.array([[95, 54, 26, 6, 10],[70, 40, 20, 5, 8],
             [46, 26, 14, 4, 6],[25, 14, 8, 3, 4],
             [9, 5, 3, 2, 2]])

def secondQ2(A):
    n, m = A.shape  

    Q = np.empty((n, n))
    u = np.empty((n, n))

    u[:, 0] = A[:, 0]
    Q[:, 0] = u[:, 0] / np.linalg.norm(u[:, 0])

    for i in range(1, n):

        u[:, i] = A[:, i]
        for j in range(i):
            u[:, i] -= (A[:, i] @ Q[:, j]) * Q[:, j]

        Q[:, i] = u[:, i] / np.linalg.norm(u[:, i]) 

    R = np.zeros((n, m))
    for i in range(n):
        for j in range(i, m):
            R[i, j] = A[:, j] @ Q[:, i]

    return Q, R

In [20]:
Q, R = secondQ2(A)

In [21]:
Q

array([[ 7.34099782e-01, -2.66652690e-02, -6.78517850e-01,
        -5.76776913e-13, -2.65706521e-12],
       [ 5.40915629e-01,  5.79162849e-01,  5.62464955e-01,
         1.84448932e-01,  1.46943672e-01],
       [ 3.55458842e-01, -4.32079264e-01,  4.01557259e-01,
        -4.71237270e-01, -5.51038769e-01],
       [ 1.93184153e-01, -6.05828118e-01,  2.32817772e-01,
         4.04597656e-02,  7.34718358e-01],
       [ 6.95462951e-02, -3.31872202e-01,  8.82856385e-02,
         8.61555009e-01, -3.67359179e-01]])

In [22]:
R

array([[ 1.29410201e+02,  7.35722529e+01,  3.66354428e+01,
         9.24965725e+00,  1.47129051e+01],
       [ 0.00000000e+00,  3.51573929e-01, -1.00139125e+00,
        -1.47372318e+00, -1.31288235e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.35703570e+00,
         1.22247130e+00,  1.23172705e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         8.81784892e-01,  5.33116912e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  7.34718358e-02]])

In [23]:
Q @ R

array([[95., 54., 26.,  6., 10.],
       [70., 40., 20.,  5.,  8.],
       [46., 26., 14.,  4.,  6.],
       [25., 14.,  8.,  3.,  4.],
       [ 9.,  5.,  3.,  2.,  2.]])

# Q2

In [25]:
A = np.array([[4, -1, 0, 0, 0, 0, 0, 0, 0, 0],
             [-1, 4, -1, 0, 0, 0, 0, 0, 0, 0],
             [0, -1, 4, -1, 0, 0, 0, 0, 0, 0],
             [0, 0, -1, 4, -1, 0, 0, 0, 0, 0],
             [0, 0, 0, -1, 4, -1, 0, 0, 0, 0],
             [0, 0, 0, 0, -1, 4, -1, 0, 0, 0],
             [0, 0, 0, 0, 0, -1, 4, -1, 0, 0],
             [0, 0, 0, 0, 0, 0, -1, 4, -1, 0],
             [0, 0, 0, 0, 0, 0, 0, -1, 4, -1],
             [0, 0, 0, 0, 0, 0, 0, 0, -1, 4]])
             
             

In [26]:
A

array([[ 4, -1,  0,  0,  0,  0,  0,  0,  0,  0],
       [-1,  4, -1,  0,  0,  0,  0,  0,  0,  0],
       [ 0, -1,  4, -1,  0,  0,  0,  0,  0,  0],
       [ 0,  0, -1,  4, -1,  0,  0,  0,  0,  0],
       [ 0,  0,  0, -1,  4, -1,  0,  0,  0,  0],
       [ 0,  0,  0,  0, -1,  4, -1,  0,  0,  0],
       [ 0,  0,  0,  0,  0, -1,  4, -1,  0,  0],
       [ 0,  0,  0,  0,  0,  0, -1,  4, -1,  0],
       [ 0,  0,  0,  0,  0,  0,  0, -1,  4, -1],
       [ 0,  0,  0,  0,  0,  0,  0,  0, -1,  4]])

In [27]:
b = np.array([2, 4, 6, 8, 10, 12, 14, 16, 18, 31])

In [28]:
np.transpose(b)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 31])

In [29]:
  
def secondQ(a, x ,b):
    
    n = a.shape[0]         
   
    for j in range(0, n):        
        
        d = b[j]                  
          
       
        for i in range(0, n):     
            if(j != i):
                d-=a[j][i] * x[i]
             
        x[j] = d / a[j][j]
             
    return x    
   

In [32]:
x = [0,0,0,0,0,0,0,0,0,0]
f =[]

for i in range(0, 100): 
   
    v1= np.array(x) 
    # print('v1 = ',v1)
   

    x = secondQ(A, x, b)
    
    v2 = np.array(x)
    nor = lg.norm(v2 - v1, np.inf)
    if nor < 0.00001:
        print(nor)
        print(v2)
        break

5.078884333542533e-06
[ 0.99999831  1.99999831  2.99999877  3.99999924  4.99999958  5.99999979
  6.9999999   7.99999996  8.99999999 10.        ]


In [114]:
v2 =  np.array( [0.5, 1.125, 1.78125, 2.4453125, 3.111328125, 3.77783203125, 4.4444580078125, 5.111114501953125, 5.777778625488281, 9.19444465637207])
v1 = np.array([0.5, 1.125, 1.78125, 2.4453125, 3.111328125, 3.77783203125, 4.4444580078125, 5.111114501953125, 5.777778625488281, 9.19444465637207])

In [33]:
lg.norm(v2-v1, np.inf)

5.078884333542533e-06

# Q3

In [47]:
import numpy as np
A = np.array([[i*j+ i*i + j*j for i in range(1,11)] 
for j in range(1,11)])
A

array([[  3,   7,  13,  21,  31,  43,  57,  73,  91, 111],
       [  7,  12,  19,  28,  39,  52,  67,  84, 103, 124],
       [ 13,  19,  27,  37,  49,  63,  79,  97, 117, 139],
       [ 21,  28,  37,  48,  61,  76,  93, 112, 133, 156],
       [ 31,  39,  49,  61,  75,  91, 109, 129, 151, 175],
       [ 43,  52,  63,  76,  91, 108, 127, 148, 171, 196],
       [ 57,  67,  79,  93, 109, 127, 147, 169, 193, 219],
       [ 73,  84,  97, 112, 129, 148, 169, 192, 217, 244],
       [ 91, 103, 117, 133, 151, 171, 193, 217, 243, 271],
       [111, 124, 139, 156, 175, 196, 219, 244, 271, 300]])

In [48]:
A.transpose()

array([[  3,   7,  13,  21,  31,  43,  57,  73,  91, 111],
       [  7,  12,  19,  28,  39,  52,  67,  84, 103, 124],
       [ 13,  19,  27,  37,  49,  63,  79,  97, 117, 139],
       [ 21,  28,  37,  48,  61,  76,  93, 112, 133, 156],
       [ 31,  39,  49,  61,  75,  91, 109, 129, 151, 175],
       [ 43,  52,  63,  76,  91, 108, 127, 148, 171, 196],
       [ 57,  67,  79,  93, 109, 127, 147, 169, 193, 219],
       [ 73,  84,  97, 112, 129, 148, 169, 192, 217, 244],
       [ 91, 103, 117, 133, 151, 171, 193, 217, 243, 271],
       [111, 124, 139, 156, 175, 196, 219, 244, 271, 300]])

In [49]:
def householder_vectorized(a):
    """Use this version of householder to reproduce the output of np.linalg.qr 
    exactly (specifically, to match the sign convention it uses)
    
    based on https://rosettacode.org/wiki/QR_decomposition#Python
    """
    v = a / (a[0] + np.copysign(np.linalg.norm(a), a[0]))
    v[0] = 1
    tau = 2 / (v.T @ v)
    
    return v,tau

In [50]:
import numpy as np
from typing import Union

def qr_decomposition(A: np.ndarray) -> Union[np.ndarray, np.ndarray]:
    m,n = A.shape
    R = A.copy()
    Q = np.identity(m)
    
    for j in range(0, n):
        # Apply Householder transformation.
        v, tau = householder_vectorized(R[j:, j, np.newaxis])
        
        H = np.identity(m)
        H[j:, j:] -= tau * (v @ v.T)
        R = H @ R
        Q = H @ Q
        
    return Q[:n].T, np.triu(R[:n])
    



m = 5
n = 4

# A = np.random.rand(m, n)
q, r = np.linalg.qr(A)
Q, R = qr_decomposition(A)

with np.printoptions(linewidth=9999, precision=20, suppress=True):
    print("**** Q from qr_decomposition")
    print(Q)
    print("**** Q from np.linalg.qr")
    print(q)
    print()
    
    print("**** R from qr_decomposition")
    print(R)
    print("**** R from np.linalg.qr")
    print(r)


**** Q from qr_decomposition
[[-0.016600702335237028  -0.3648374624040066     0.6962757075257143    -0.5535656604057075    -0.1622108109142021     0.14962076218459608    0.02657075327895796    0.1313601017362068    -0.09155133595234487    0.01847683444155948  ]
 [-0.0387349721155534    -0.4069083681102323     0.3342350380868757     0.5950853500746752     0.22500956568390348    0.09852197703410538   -0.3637196238253713     0.025545795525506062   0.3197678416371238     0.26749511726517017  ]
 [-0.07193637678602775   -0.4187402215735144     0.053057684314292704   0.29000370675603915   -0.0007719917697299707 -0.31532299837126554    0.6993111050015229     0.07720176120457256    0.05742090010391071   -0.36720843424546334  ]
 [-0.1162049163466602    -0.4003330227938546    -0.14725635379210705   -0.03878683785251088    0.16294454296691996   -0.1695081635666999    -0.045507981643029334  -0.5604972257303966    -0.5966801697212237     0.27477582275950374  ]
 [-0.1715405907974508    -0.35168677177

In [51]:
q @ r

array([[  3.,   7.,  13.,  21.,  31.,  43.,  57.,  73.,  91., 111.],
       [  7.,  12.,  19.,  28.,  39.,  52.,  67.,  84., 103., 124.],
       [ 13.,  19.,  27.,  37.,  49.,  63.,  79.,  97., 117., 139.],
       [ 21.,  28.,  37.,  48.,  61.,  76.,  93., 112., 133., 156.],
       [ 31.,  39.,  49.,  61.,  75.,  91., 109., 129., 151., 175.],
       [ 43.,  52.,  63.,  76.,  91., 108., 127., 148., 171., 196.],
       [ 57.,  67.,  79.,  93., 109., 127., 147., 169., 193., 219.],
       [ 73.,  84.,  97., 112., 129., 148., 169., 192., 217., 244.],
       [ 91., 103., 117., 133., 151., 171., 193., 217., 243., 271.],
       [111., 124., 139., 156., 175., 196., 219., 244., 271., 300.]])

In [52]:
Q @ R

array([[  3.,   7.,  13.,  21.,  31.,  43.,  57.,  73.,  91., 111.],
       [  7.,  12.,  19.,  28.,  39.,  52.,  67.,  84., 103., 124.],
       [ 13.,  19.,  27.,  37.,  49.,  63.,  79.,  97., 117., 139.],
       [ 21.,  28.,  37.,  48.,  61.,  76.,  93., 112., 133., 156.],
       [ 31.,  39.,  49.,  61.,  75.,  91., 109., 129., 151., 175.],
       [ 43.,  52.,  63.,  76.,  91., 108., 127., 148., 171., 196.],
       [ 57.,  67.,  79.,  93., 109., 127., 147., 169., 193., 219.],
       [ 73.,  84.,  97., 112., 129., 148., 169., 192., 217., 244.],
       [ 91., 103., 117., 133., 151., 171., 193., 217., 243., 271.],
       [111., 124., 139., 156., 175., 196., 219., 244., 271., 300.]])