In [4]:
import numpy as np 
import scipy.linalg as lg 

## LU Decoposition

In [14]:
A = np.array([[95, 54, 26, 6, 10],[70, 40, 20, 5, 8],
             [46, 26, 14, 4, 6],[25, 14, 8, 3, 4],
             [9, 5, 3, 2, 2]])

In [15]:
A

array([[95, 54, 26,  6, 10],
       [70, 40, 20,  5,  8],
       [46, 26, 14,  4,  6],
       [25, 14,  8,  3,  4],
       [ 9,  5,  3,  2,  2]])

In [16]:
A, L, U = lg.lu(A)

In [17]:
A


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.]])

In [18]:
L

array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.73684211,  1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.48421053, -0.7       ,  1.        ,  0.        ,  0.        ],
       [ 0.09473684, -0.55      ,  0.5       ,  1.        ,  0.        ],
       [ 0.26315789, -1.        ,  1.        ,  0.5       ,  1.        ]])

In [13]:
U

array([[95.        , 54.        , 26.        ,  6.        , 10.        ],
       [ 0.        ,  0.21052632,  0.84210526,  0.57894737,  0.63157895],
       [ 0.        ,  0.        ,  2.        ,  1.5       ,  1.6       ],
       [ 0.        ,  0.        ,  0.        ,  1.        ,  0.6       ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.1       ]])

In [24]:
def lu()

array([1., 0., 0., 0., 0.])