In [101]:
import numpy as np 
import scipy.linalg as lg 
import math

# Q1

## LU Decoposition

  \begin{bmatrix}a_{11}&a_{12}&a_{13}\\a_{21}&a_{22}&a_{23}\\a_{31}&a_{32}&a_{33}\end{bmatrix} 
 
\begin{bmatrix}\ell _{11}&0&0\\\ell _{21}&\ell _{22}&0\\\ell _{31}&\ell _{32}&\ell _{33}\end{bmatrix}

\begin{bmatrix}u_{11}&u_{12}&u_{13}\\0&u_{22}&u_{23}\\0&0&u_{33}\end{bmatrix}

In [5]:
A = np.array([[95, 54, 26, 6, 10],
              [70, 40, 20, 5, 8],
              [46, 26, 14, 4, 6],
              [25, 14, 8, 3, 4],
              [9, 5, 3, 2, 2]])

In [6]:
A

array([[95, 54, 26,  6, 10],
       [70, 40, 20,  5,  8],
       [46, 26, 14,  4,  6],
       [25, 14,  8,  3,  4],
       [ 9,  5,  3,  2,  2]])

In [7]:
A, L,U= lg.lu(A)

In [8]:
L

array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.73684211,  1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.48421053, -0.7       ,  1.        ,  0.        ,  0.        ],
       [ 0.09473684, -0.55      ,  0.5       ,  1.        ,  0.        ],
       [ 0.26315789, -1.        ,  1.        ,  0.5       ,  1.        ]])

In [9]:
L

array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.73684211,  1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.48421053, -0.7       ,  1.        ,  0.        ,  0.        ],
       [ 0.09473684, -0.55      ,  0.5       ,  1.        ,  0.        ],
       [ 0.26315789, -1.        ,  1.        ,  0.5       ,  1.        ]])

In [10]:
L @ U

array([[95., 54., 26.,  6., 10.],
       [70., 40., 20.,  5.,  8.],
       [46., 26., 14.,  4.,  6.],
       [ 9.,  5.,  3.,  2.,  2.],
       [25., 14.,  8.,  3.,  4.]])

In [11]:
U

array([[95.        , 54.        , 26.        ,  6.        , 10.        ],
       [ 0.        ,  0.21052632,  0.84210526,  0.57894737,  0.63157895],
       [ 0.        ,  0.        ,  2.        ,  1.5       ,  1.6       ],
       [ 0.        ,  0.        ,  0.        ,  1.        ,  0.6       ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.1       ]])

In [12]:
A

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.]])

In [13]:
A = np.array([[95, 54, 26, 6, 10],[70, 40, 20, 5, 8],
             [46, 26, 14, 4, 6],[25, 14, 8, 3, 4],
             [9, 5, 3, 2, 2]])

In [14]:
n = A.shape[0]

u = np.zeros((n,n), dtype=np.double)
l = np.eye(n, dtype=np.double)

def firstQ1(A):
    
    n = A.shape[0]
    for k in range(n):
        
        u[k, k:] = A[k, k:] - l[k,:k] @ u[:k,k:]
        
        l[(k+1):,k] = (A[(k+1):,k]- l[(k+1):,:] @ u[:,k] )/ u[k, k]
        
        
        
    return l,u


firstQ1(A)

(array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.73684211,  1.        ,  0.        ,  0.        ,  0.        ],
        [ 0.48421053, -0.7       ,  1.        ,  0.        ,  0.        ],
        [ 0.26315789, -1.        ,  1.        ,  1.        ,  0.        ],
        [ 0.09473684, -0.55      ,  0.5       ,  2.        ,  1.        ]]),
 array([[95.        , 54.        , 26.        ,  6.        , 10.        ],
        [ 0.        ,  0.21052632,  0.84210526,  0.57894737,  0.63157895],
        [ 0.        ,  0.        ,  2.        ,  1.5       ,  1.6       ],
        [ 0.        ,  0.        ,  0.        ,  0.5       ,  0.4       ],
        [ 0.        ,  0.        ,  0.        ,  0.        , -0.2       ]]))

In [15]:
l

array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.73684211,  1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.48421053, -0.7       ,  1.        ,  0.        ,  0.        ],
       [ 0.26315789, -1.        ,  1.        ,  1.        ,  0.        ],
       [ 0.09473684, -0.55      ,  0.5       ,  2.        ,  1.        ]])

In [16]:
u

array([[95.        , 54.        , 26.        ,  6.        , 10.        ],
       [ 0.        ,  0.21052632,  0.84210526,  0.57894737,  0.63157895],
       [ 0.        ,  0.        ,  2.        ,  1.5       ,  1.6       ],
       [ 0.        ,  0.        ,  0.        ,  0.5       ,  0.4       ],
       [ 0.        ,  0.        ,  0.        ,  0.        , -0.2       ]])

In [17]:
l @ u  

array([[95., 54., 26.,  6., 10.],
       [70., 40., 20.,  5.,  8.],
       [46., 26., 14.,  4.,  6.],
       [25., 14.,  8.,  3.,  4.],
       [ 9.,  5.,  3.,  2.,  2.]])

### QR Decompostion


In [18]:
A = np.array([[95, 54, 26, 6, 10],[70, 40, 20, 5, 8],
             [46, 26, 14, 4, 6],[25, 14, 8, 3, 4],
             [9, 5, 3, 2, 2]])

In [19]:
Q1 , R1 = lg.qr(A)

In [20]:
Q1

array([[-7.34099782e-01,  2.66652690e-02,  6.78517850e-01,
        -7.67290867e-16,  2.74528934e-16],
       [-5.40915629e-01, -5.79162849e-01, -5.62464955e-01,
        -1.84448932e-01, -1.46943672e-01],
       [-3.55458842e-01,  4.32079264e-01, -4.01557259e-01,
         4.71237270e-01,  5.51038769e-01],
       [-1.93184153e-01,  6.05828118e-01, -2.32817772e-01,
        -4.04597656e-02, -7.34718358e-01],
       [-6.95462951e-02,  3.31872202e-01, -8.82856385e-02,
        -8.61555009e-01,  3.67359179e-01]])

In [21]:
R1

array([[-1.29410201e+02, -7.35722529e+01, -3.66354428e+01,
        -9.24965725e+00, -1.47129051e+01],
       [ 0.00000000e+00, -3.51573929e-01,  1.00139125e+00,
         1.47372318e+00,  1.31288235e+00],
       [ 0.00000000e+00,  0.00000000e+00, -1.35703570e+00,
        -1.22247130e+00, -1.23172705e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -8.81784892e-01, -5.33116912e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00, -7.34718358e-02]])

In [22]:
Q1 @ R1

array([[95., 54., 26.,  6., 10.],
       [70., 40., 20.,  5.,  8.],
       [46., 26., 14.,  4.,  6.],
       [25., 14.,  8.,  3.,  4.],
       [ 9.,  5.,  3.,  2.,  2.]])

In [23]:
A

array([[95, 54, 26,  6, 10],
       [70, 40, 20,  5,  8],
       [46, 26, 14,  4,  6],
       [25, 14,  8,  3,  4],
       [ 9,  5,  3,  2,  2]])

In [24]:
n, m =np.shape(A)
m

5

In [25]:
A = np.array([[95, 54, 26, 6, 10],[70, 40, 20, 5, 8],
             [46, 26, 14, 4, 6],[25, 14, 8, 3, 4],
             [9, 5, 3, 2, 2]])

def secondQ1(A):
    n, m = A.shape

    Q = np.empty((n, n))

    v = np.empty((n, n))

    v[:, 0] = A[:, 0]
    Q[:, 0] =v[:, 0] / np.linalg.norm(v[:, 0])

    for i in range(1, n):

        v[:, i] = A[:, i]
        
        for j in range(i):


            v[:, i] -= (A[:, i] @ Q[:, j]) * Q[:, j]



        Q[:, i] = v[:, i]/ np.linalg.norm(v[:, i]) 

    R = np.zeros((n, m))
    for i in range(n):
        for j in range(i, m):
            R[i, j] = A[:, j]@ Q[:, i]

    return Q, R

In [26]:
Q, R = secondQ1(A)

In [27]:
Q 

array([[ 7.34099782e-01, -2.66652690e-02, -6.78517850e-01,
        -5.76776913e-13, -2.65706521e-12],
       [ 5.40915629e-01,  5.79162849e-01,  5.62464955e-01,
         1.84448932e-01,  1.46943672e-01],
       [ 3.55458842e-01, -4.32079264e-01,  4.01557259e-01,
        -4.71237270e-01, -5.51038769e-01],
       [ 1.93184153e-01, -6.05828118e-01,  2.32817772e-01,
         4.04597656e-02,  7.34718358e-01],
       [ 6.95462951e-02, -3.31872202e-01,  8.82856385e-02,
         8.61555009e-01, -3.67359179e-01]])

In [28]:
R

array([[ 1.29410201e+02,  7.35722529e+01,  3.66354428e+01,
         9.24965725e+00,  1.47129051e+01],
       [ 0.00000000e+00,  3.51573929e-01, -1.00139125e+00,
        -1.47372318e+00, -1.31288235e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.35703570e+00,
         1.22247130e+00,  1.23172705e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         8.81784892e-01,  5.33116912e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  7.34718358e-02]])

In [29]:
Q @ R

array([[95., 54., 26.,  6., 10.],
       [70., 40., 20.,  5.,  8.],
       [46., 26., 14.,  4.,  6.],
       [25., 14.,  8.,  3.,  4.],
       [ 9.,  5.,  3.,  2.,  2.]])

# Q2

In [30]:
A = np.array([[4, -1, 0, 0, 0, 0, 0, 0, 0, 0],
             [-1, 4, -1, 0, 0, 0, 0, 0, 0, 0],
             [0, -1, 4, -1, 0, 0, 0, 0, 0, 0],
             [0, 0, -1, 4, -1, 0, 0, 0, 0, 0],
             [0, 0, 0, -1, 4, -1, 0, 0, 0, 0],
             [0, 0, 0, 0, -1, 4, -1, 0, 0, 0],
             [0, 0, 0, 0, 0, -1, 4, -1, 0, 0],
             [0, 0, 0, 0, 0, 0, -1, 4, -1, 0],
             [0, 0, 0, 0, 0, 0, 0, -1, 4, -1],
             [0, 0, 0, 0, 0, 0, 0, 0, -1, 4]])
             
             

In [31]:
A

array([[ 4, -1,  0,  0,  0,  0,  0,  0,  0,  0],
       [-1,  4, -1,  0,  0,  0,  0,  0,  0,  0],
       [ 0, -1,  4, -1,  0,  0,  0,  0,  0,  0],
       [ 0,  0, -1,  4, -1,  0,  0,  0,  0,  0],
       [ 0,  0,  0, -1,  4, -1,  0,  0,  0,  0],
       [ 0,  0,  0,  0, -1,  4, -1,  0,  0,  0],
       [ 0,  0,  0,  0,  0, -1,  4, -1,  0,  0],
       [ 0,  0,  0,  0,  0,  0, -1,  4, -1,  0],
       [ 0,  0,  0,  0,  0,  0,  0, -1,  4, -1],
       [ 0,  0,  0,  0,  0,  0,  0,  0, -1,  4]])

In [32]:
b = np.array([2, 4, 6, 8, 10, 12, 14, 16, 18, 31])

In [33]:
np.transpose(b)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 31])

In [34]:
  
def secondQ(a,x ,b):
    
    n = a.shape[0]         
   
    for j in range(0, n):        
        
        d = b[j]                  
          
       
        for i in range(0, n):     
            if(j != i):
                d-=a[j][i]* x[i]
             
        x[j] = d /a[j][j]
             
    return x    
   

In [35]:
x = [0,0,0,0,0,0,0,0,0,0]


for i in range(0, 100): 
   
    v1= np.array(x) 
    # print('v1 = ',v1)
   

    x = secondQ(A, x, b)
    
    v2 = np.array(x)
    nor = lg.norm(v2 - v1, np.inf)
    if nor < 0.00001:
        print(i)
        
        print('##################')
        print(nor)
        
        print(v2)
        break

12
##################
5.078884333542533e-06
[ 0.99999831  1.99999831  2.99999877  3.99999924  4.99999958  5.99999979
  6.9999999   7.99999996  8.99999999 10.        ]


In [36]:
lg.norm(v2-v1, np.inf)

5.078884333542533e-06

# Q3

In [37]:
import numpy as np
A = np.array([[i*j+ i*i + j*j for i in range(1,11)] 
for j in range(1,11)])
A

array([[  3,   7,  13,  21,  31,  43,  57,  73,  91, 111],
       [  7,  12,  19,  28,  39,  52,  67,  84, 103, 124],
       [ 13,  19,  27,  37,  49,  63,  79,  97, 117, 139],
       [ 21,  28,  37,  48,  61,  76,  93, 112, 133, 156],
       [ 31,  39,  49,  61,  75,  91, 109, 129, 151, 175],
       [ 43,  52,  63,  76,  91, 108, 127, 148, 171, 196],
       [ 57,  67,  79,  93, 109, 127, 147, 169, 193, 219],
       [ 73,  84,  97, 112, 129, 148, 169, 192, 217, 244],
       [ 91, 103, 117, 133, 151, 171, 193, 217, 243, 271],
       [111, 124, 139, 156, 175, 196, 219, 244, 271, 300]])

In [38]:
A.transpose()

array([[  3,   7,  13,  21,  31,  43,  57,  73,  91, 111],
       [  7,  12,  19,  28,  39,  52,  67,  84, 103, 124],
       [ 13,  19,  27,  37,  49,  63,  79,  97, 117, 139],
       [ 21,  28,  37,  48,  61,  76,  93, 112, 133, 156],
       [ 31,  39,  49,  61,  75,  91, 109, 129, 151, 175],
       [ 43,  52,  63,  76,  91, 108, 127, 148, 171, 196],
       [ 57,  67,  79,  93, 109, 127, 147, 169, 193, 219],
       [ 73,  84,  97, 112, 129, 148, 169, 192, 217, 244],
       [ 91, 103, 117, 133, 151, 171, 193, 217, 243, 271],
       [111, 124, 139, 156, 175, 196, 219, 244, 271, 300]])

In [39]:
lg.det(A)

-3.640471533408651e-93

In [86]:
A = np.array([[1, 1, -2,2],
             [1, -1, -1 , 2],
              [-2, -1, 1,2],
              [2,2,2,1]])


A

array([[ 1,  1, -2,  2],
       [ 1, -1, -1,  2],
       [-2, -1,  1,  2],
       [ 2,  2,  2,  1]])

In [88]:
def genvec_house(a):


    u = a/ (a[0] +np.copysign(np.linalg.norm(a), a[0]))

    u[0] = 1
    tau = 2*(u@ u.T)/ (u.T @ u)
    
    return u,tau

In [108]:
def gen_U(a):
  

    norm2 = 0
    t = a.shape[0]
    
    l = [[0] for i in range(t)]
    l[0] = [1]
    for i in a:
        norm2 += i**2
        
    norm2 = math.sqrt(norm2)    
        
    if a[0] <0:
           u=   a - norm2 * np.array(l)
    elif a[0] >= 0:
        u = a+ norm2 * np.array(l)
        
    i = np.identity(t) 
    htua = i -  (2*(u@ u.T)/ (u.T @ u))
    return u, htua

In [127]:
import numpy as np


def qr(A):
    m,n = A.shape
    R = A.copy()
    Q = np.identity(m)
    
    for j in range(0, n):

        u, tau = genvec_house(R[j:, j,   np.newaxis])
        
        H = np.identity(m)
        H[j:, j:] =H[j:, j:] - tau


        R = H@R

        Q = H @Q
        
    return Q.T, np.triu(R)
    

A = np.array([[i*j+ i*i + j*j for i in range(1,11)] 
for j in range(1,11)])

q, r = lg.qr(A)
Q, R = qr(A)

# with np.printoptions(linewidth=9999, precision=20, suppress=True):
#     print("Q from qr")
#     print(Q)
#     print("Q from lg.qr")
#     print(q)
#     print()
    
#     print("R from qr")
#     print(R)
#     print("R from np.linalg.qr")
#     print(r)


In [128]:
Q

array([[-0.0166007 , -0.36483746,  0.69627571, -0.02773998, -0.21718188,
        -0.10377545, -0.05851544, -0.37050986,  0.09338993,  0.41675901],
       [-0.03873497, -0.40690837,  0.33423504,  0.15562774,  0.20634669,
         0.33159027,  0.1126481 ,  0.31210429,  0.41167828, -0.51466822],
       [-0.07193638, -0.41874022,  0.05305768,  0.27179087,  0.01902161,
        -0.18968417,  0.01598325,  0.50813265, -0.65772929,  0.12406615],
       [-0.11620492, -0.40033302, -0.14725635, -0.36356984,  0.27716862,
         0.06821922, -0.3606322 , -0.46431936, -0.34134572, -0.35877733],
       [-0.17154059, -0.35168677, -0.26670708, -0.61676711, -0.29847452,
         0.03620436,  0.49554178,  0.16712187,  0.11399842,  0.13590842],
       [-0.2379434 , -0.27280147, -0.30529448,  0.34827434, -0.03423699,
        -0.68979039,  0.04349649, -0.18446272,  0.34893271, -0.14073785],
       [-0.31541334, -0.16367711, -0.26301857,  0.01688985,  0.16585706,
         0.25251075, -0.55452587,  0.23814088

In [129]:
Qt = Q.T
Qt

array([[-0.0166007 , -0.03873497, -0.07193638, -0.11620492, -0.17154059,
        -0.2379434 , -0.31541334, -0.40395042, -0.50355464, -0.61422599],
       [-0.36483746, -0.40690837, -0.41874022, -0.40033302, -0.35168677,
        -0.27280147, -0.16367711, -0.02431371,  0.14528875,  0.34513027],
       [ 0.69627571,  0.33423504,  0.05305768, -0.14725635, -0.26670708,
        -0.30529448, -0.26301857, -0.13987935,  0.06412319,  0.34898905],
       [-0.02773998,  0.15562774,  0.27179087, -0.36356984, -0.61676711,
         0.34827434,  0.01688985,  0.41435747,  0.09487458, -0.29373791],
       [-0.21718188,  0.20634669,  0.01902161,  0.27716862, -0.29847452,
        -0.03423699,  0.16585706,  0.17645329, -0.71345679,  0.4185029 ],
       [-0.10377545,  0.33159027, -0.18968417,  0.06821922,  0.03620436,
        -0.68979039,  0.25251075,  0.43063435,  0.15906957, -0.29497851],
       [-0.05851544,  0.1126481 ,  0.01598325, -0.3606322 ,  0.49554178,
         0.04349649, -0.55452587,  0.47342488

In [130]:
A

array([[  3,   7,  13,  21,  31,  43,  57,  73,  91, 111],
       [  7,  12,  19,  28,  39,  52,  67,  84, 103, 124],
       [ 13,  19,  27,  37,  49,  63,  79,  97, 117, 139],
       [ 21,  28,  37,  48,  61,  76,  93, 112, 133, 156],
       [ 31,  39,  49,  61,  75,  91, 109, 129, 151, 175],
       [ 43,  52,  63,  76,  91, 108, 127, 148, 171, 196],
       [ 57,  67,  79,  93, 109, 127, 147, 169, 193, 219],
       [ 73,  84,  97, 112, 129, 148, 169, 192, 217, 244],
       [ 91, 103, 117, 133, 151, 171, 193, 217, 243, 271],
       [111, 124, 139, 156, 175, 196, 219, 244, 271, 300]])

In [131]:
Qt @ A @ Q

array([[ 1.15974417e+03,  3.66431029e+02, -3.98906795e+01,
         6.07663692e-13, -2.59346198e-13, -2.98086914e-13,
        -7.35427872e-14,  2.03640861e-14, -1.00106939e-13,
        -2.79311906e-14],
       [ 3.66431029e+02, -6.56766185e+00,  5.29514863e+00,
        -8.98508046e-14,  8.22669395e-14,  1.49529802e-14,
        -1.09824334e-14, -4.62027766e-15, -3.91587905e-14,
         3.57271485e-14],
       [-3.98906795e+01,  5.29514863e+00,  1.82349503e+00,
        -2.82721382e-14,  1.97692787e-14,  2.57328659e-14,
        -3.27418619e-15, -2.22457607e-15,  4.96697499e-15,
        -2.05211910e-15],
       [ 6.05491095e-13, -8.17365951e-14, -2.81054676e-14,
        -5.19613963e-15, -1.20026675e-15, -1.83092931e-16,
        -7.77660789e-15,  1.07696932e-14,  4.79666766e-15,
         2.98100897e-15],
       [-2.52368589e-13,  2.91197235e-14,  1.00196668e-15,
        -4.08300678e-15, -6.28000317e-15, -4.96615408e-16,
         2.77021305e-15,  1.66349446e-15,  6.60447164e-15,
         4.

In [125]:
Q @ R

array([[1.86765048e+02, 4.45368099e+02, 8.07880355e+02, 1.31211137e+03,
        2.00217650e+03, 2.92733806e+03, 4.13740656e+03, 5.67153547e+03,
        7.53356732e+03, 9.63233520e+03],
       [7.11620492e+00, 1.69696134e+01, 3.07822166e+01, 4.99946510e+01,
        7.62878195e+01, 1.11538737e+02, 1.57645305e+02, 2.16099367e+02,
        2.87047333e+02, 3.67015520e+02],
       [1.32158091e+01, 3.15149963e+01, 5.71669737e+01, 9.28472090e+01,
        1.41677379e+02, 2.07143368e+02, 2.92769852e+02, 4.01327396e+02,
        5.33087904e+02, 6.81600251e+02],
       [2.13486147e+01, 5.09088402e+01, 9.23466498e+01, 1.49983953e+02,
        2.28863458e+02, 3.34616210e+02, 4.72935915e+02, 6.48298101e+02,
        8.61141999e+02, 1.10104656e+03],
       [3.15146218e+01, 7.51511451e+01, 1.36321245e+02, 2.21404883e+02,
        3.37846058e+02, 4.93957262e+02, 6.98143494e+02, 9.57011482e+02,
        1.27120962e+03, 1.62535445e+03],
       [4.37138302e+01, 1.04241911e+02, 1.89090759e+02, 3.07109999e+02,
   

In [121]:
Q @ Qt

array([[13.77636333,  0.52491312,  0.97483866,  1.57473937,  2.32461526,
         3.22446633,  4.27429257,  5.474094  ,  6.8238706 ,  8.32362238],
       [ 0.52491312,  0.02000047,  0.03714374,  0.06000142,  0.08857352,
         0.12286005,  0.162861  ,  0.20857636,  0.26000615,  0.31715036],
       [ 0.97483866,  0.03714374,  0.06898122,  0.11143121,  0.16449369,
         0.22816866,  0.30245614,  0.3873561 ,  0.48286857,  0.58899353],
       [ 1.57473937,  0.06000142,  0.11143121,  0.18000426,  0.26572057,
         0.36858015,  0.48858299,  0.62572909,  0.78001846,  0.95145109],
       [ 2.32461526,  0.08857352,  0.16449369,  0.26572057,  0.39225418,
         0.54409451,  0.72124156,  0.92369533,  1.15145582,  1.40452303],
       [ 3.22446633,  0.12286005,  0.22816866,  0.36858015,  0.54409451,
         0.75471174,  1.00043184,  1.28125481,  1.59718065,  1.94820937],
       [ 4.27429257,  0.162861  ,  0.30245614,  0.48858299,  0.72124156,
         1.00043184,  1.32615383,  1.69840754

In [80]:
A

array([[ 1,  1, -2,  2],
       [ 1, -1, -1,  2],
       [-2, -1,  1,  2],
       [ 2,  2,  2,  1]])

In [50]:
lg.eig(A)

(array([ 1.26638844e+03+0.00000000e+00j, -1.14395295e+02+0.00000000e+00j,
         3.00685699e+00+0.00000000e+00j,  5.78825030e-15+1.78688579e-14j,
         5.78825030e-15-1.78688579e-14j,  1.42219202e-14+0.00000000e+00j,
        -7.36684487e-15+0.00000000e+00j,  3.77882149e-15+9.22268350e-15j,
         3.77882149e-15-9.22268350e-15j,  2.85270251e-15+0.00000000e+00j]),
 array([[-1.37079103e-01+0.j        , -4.38735306e-01+0.j        ,
          6.37889072e-01+0.j        ,  1.04833245e-01-0.01538052j,
          1.04833245e-01+0.01538052j, -1.21404377e-01+0.j        ,
         -4.13284265e-02+0.j        , -1.54594105e-01+0.01711409j,
         -1.54594105e-01-0.01711409j,  2.75220666e-01+0.j        ],
        [-1.59417948e-01+0.j        , -4.22388504e-01+0.j        ,
          2.73791432e-01+0.j        , -3.54276553e-02+0.0140644j ,
         -3.54276553e-02-0.0140644j , -6.44442592e-02+0.j        ,
         -3.58456229e-02+0.j        ,  7.01783750e-02-0.11640481j,
          7.01783750e-02