In [334]:
import numpy as np
import math

In [352]:
A = np.array([[1, 1, -2, 2],
             [1, -1, -1, 2],
             [-2, -1, 1, 2],
             [2, 2, 2, 1]])

In [353]:

# A = np.array([[i*j+ i*i + j*j for i in range(1,11)] 
# for j in range(1,11)])
A

array([[ 1,  1, -2,  2],
       [ 1, -1, -1,  2],
       [-2, -1,  1,  2],
       [ 2,  2,  2,  1]])

In [354]:


c= A[1:, 0, np.newaxis]
c

array([[ 1],
       [-2],
       [ 2]])

In [355]:

def gen_U(a):
  

    norm2 = 0
    t = a.shape[0]
    
    l = [[0] for i in range(t)]
    l[0] = [1]
    for i in a:
        norm2 += i**2
        
    norm2 = math.sqrt(norm2)    
        
    if a[0] <0:
           u=   a - norm2 * np.array(l)
    elif a[0] >= 0:
        u = a+ norm2 * np.array(l)
        
    i = np.identity(t) 
    h = i -  (2*(u@ u.T)/ (u.T @ u))
    return h

In [356]:
def gen_H(a):
    n = a.shape[0]
    H = a
    
    
    for i in range(n, 4):
        c = np.array([[0 for i in range(n)]])
        c2 = np.array([ 0 for i in range(n+1)])

        f = np.append(c , H, axis =0)
        H = np.insert(f, 0 , c2, axis = 1)
        H[0,0] =1 


        if H.shape[0] == 4:
            return H

        else: 
            return gen_H(H)

        
   

In [357]:
# h = np.array([[-0.90588235, -0.42352941],
#  [-0.42352941,  0.90588235]])


# for i in range(2):
#     H = gen_H(h)
#     h = H
#     if h.shape[0] == 4:

#         print(h)
#         )
        
#     else:
#         continue

In [358]:
# h = np.array([[-0.33333333,  0.66666667, -0.66666667],
#  [ 0.66666667,  0.66666667,  0.33333333],
#  [-0.66666667 , 0.33333333,  0.66666667]])
# H = gen_H(h)
# p = np.identity(4)
# # p = p @ H
# H


In [359]:

def find_t(A):
    p = np.identity(4)
    # print(p)
    for i in range(1,3):
        c= A[i:, i-1, np.newaxis]
        # print(c)
        h = gen_U(c)
        # print(h)
        H= gen_H(h)
        # print(H)
        p =H @ p
        
        
        
        
        
        A = H @ A @ H.T
    # print(p)
    # print(10000000000000000000000000000000000000000000000)
    return  A ,p
      

        

In [360]:
A , p = find_t(A)


In [361]:
A

array([[ 1.00000000e+00, -3.00000000e+00,  3.10862447e-16,
         4.44089210e-17],
       [-3.00000000e+00,  3.33333333e-01,  1.66666667e+00,
         1.33226763e-16],
       [ 3.10862447e-16,  1.66666667e+00, -2.04000000e+00,
        -1.38666667e+00],
       [ 4.44089210e-17,  2.22044605e-17, -1.38666667e+00,
         2.70666667e+00]])

In [362]:
p

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        , -0.33333333,  0.66666667, -0.66666667],
       [ 0.        , -0.93333333, -0.33333333,  0.13333333],
       [ 0.        , -0.13333333,  0.66666667,  0.73333333]])

In [346]:

A

array([[  3,   7,  13,  21,  31,  43,  57,  73,  91, 111],
       [  7,  12,  19,  28,  39,  52,  67,  84, 103, 124],
       [ 13,  19,  27,  37,  49,  63,  79,  97, 117, 139],
       [ 21,  28,  37,  48,  61,  76,  93, 112, 133, 156],
       [ 31,  39,  49,  61,  75,  91, 109, 129, 151, 175],
       [ 43,  52,  63,  76,  91, 108, 127, 148, 171, 196],
       [ 57,  67,  79,  93, 109, 127, 147, 169, 193, 219],
       [ 73,  84,  97, 112, 129, 148, 169, 192, 217, 244],
       [ 91, 103, 117, 133, 151, 171, 193, 217, 243, 271],
       [111, 124, 139, 156, 175, 196, 219, 244, 271, 300]])

In [347]:
p @ A @ p.T

array([[ 3.00000000e+00, -1.80690343e+02,  6.10622664e-16,
         1.59872116e-14,  1.02660935e-14, -7.22382223e-15,
         9.73873759e-15, -3.27515792e-15, -1.70419234e-14,
         1.06026299e-14],
       [-1.80690343e+02,  1.15406303e+03,  3.31384740e+02,
        -3.38206412e-14,  1.17865335e-14,  5.80504180e-14,
        -5.46544193e-14, -3.46302228e-15,  9.10242611e-14,
        -9.27758137e-14],
       [ 6.10622664e-16,  3.31384740e+02, -3.41696413e+00,
         3.26438668e+00,  1.23824321e-14, -6.87230301e-16,
        -2.36131162e-14,  4.53909436e-14,  5.09408415e-15,
        -4.98434015e-15],
       [ 1.59872116e-14,  1.56475047e-14,  3.26438668e+00,
         1.35393004e+00,  4.09172335e-15, -7.86774514e-15,
        -1.53441826e-15, -3.34044666e-15,  2.54090144e-15,
        -3.16839377e-15],
       [ 1.02660935e-14,  3.96624872e-15,  7.80855948e-15,
         1.21829995e-14, -6.23740176e-15,  6.07806593e-15,
        -2.59587451e-15,  4.76291779e-15, -2.29676556e-15,
        -6.

In [348]:
import scipy.linalg as lg 

In [349]:
lg.eig(A)

(array([ 1.26638844e+03+0.00000000e+00j, -1.14395295e+02+0.00000000e+00j,
         3.00685699e+00+0.00000000e+00j,  5.78825030e-15+1.78688579e-14j,
         5.78825030e-15-1.78688579e-14j,  1.42219202e-14+0.00000000e+00j,
        -7.36684487e-15+0.00000000e+00j,  3.77882149e-15+9.22268350e-15j,
         3.77882149e-15-9.22268350e-15j,  2.85270251e-15+0.00000000e+00j]),
 array([[-1.37079103e-01+0.j        , -4.38735306e-01+0.j        ,
          6.37889072e-01+0.j        ,  1.04833245e-01-0.01538052j,
          1.04833245e-01+0.01538052j, -1.21404377e-01+0.j        ,
         -4.13284265e-02+0.j        , -1.54594105e-01+0.01711409j,
         -1.54594105e-01-0.01711409j,  2.75220666e-01+0.j        ],
        [-1.59417948e-01+0.j        , -4.22388504e-01+0.j        ,
          2.73791432e-01+0.j        , -3.54276553e-02+0.0140644j ,
         -3.54276553e-02-0.0140644j , -6.44442592e-02+0.j        ,
         -3.58456229e-02+0.j        ,  7.01783750e-02-0.11640481j,
          7.01783750e-02